#ifndef __LICDEFINE_H__
#define __LICDEFINE_H__

#define LIC_SUCCESS					0
#define LIC_ERROR					1
#define LIC_PUBLICKEYEXIST			LIC_ERROR+1			
#define LIC_PUBLICKEYNOEXIST		LIC_ERROR+2
#define LIC_PRIVATEKEYEXIST			LIC_ERROR+3
#define LIC_PRIVATEKEYNOEXIST		LIC_ERROR+4
#define LIC_LICENSEDATEXIST			LIC_ERROR+5
#define LIC_LICENSEDATNOEXIST		LIC_ERROR+6
#define LIC_GENERATEWKEYFAIL		LIC_ERROR+7
#define LIC_PARAM_ERROR				LIC_ERROR+8
#define LIC_SIGN_ERROR				LIC_ERROR+9
#define LIC_SIGNOPEN_ERROR			LIC_ERROR+10
#define LIC_NTPPARAM_ERROR			LIC_ERROR+11
#define LIC_FILEOPENFAIL_ERROR		LIC_ERROR+12

#define NTP_ERROR					50
#define NTP_NETINITERROR			NTP_ERROR+1
#define NTP_INVALID_SOCKET_ERROR	NTP_ERROR+2
#define NTP_SendTo_SOCKET_ERROR		NTP_ERROR+3
#define NTP_RecvFrom_SOCKET_ERROR	NTP_ERROR+4



#endif